export enum TipoAnexoDeParagrafo {
  EXPLICACAO = 'EXPLICACAO',

  SUMARIO = 'SUMARIO',

  RESUMO = 'RESUMO',

  PLANO_DE_AULA = 'PLANO_DE_AULA',

  TXTSIMPLIFICADO = 'TXTSIMPLIFICADO',
  TXTTOPICOS = 'TXTTOPICOS',
  EXPLICATEXTO = 'EXPLICATEXTO',
  EXPLICATEXTOCTIT = 'EXPLICATEXTOCTIT',
}
